name: Srst Watcher

on:
  schedule:
    - cron: "0 * * * *"   # раз в час
  workflow_dispatch:       # запуск вручную

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Run checker
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python checker.py
